export const types = {
  FETCH_ALL : 'FETCH_ALL',
  FETCH_POST : 'FETCH_POST',
  FETCH_BY_SEARCH : 'FETCH_BY_SEARCH',
  CREATE : 'CREATE',
  UPDATE : 'UPDATE',
  DELETE : 'DELETE',
  COMMENT : 'COMMENT',

  AUTH: 'AUTH',
  LOGOUT: 'LOGOUT',

  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',


}